language: node_js
node_js:
  - "12.13"

install:
  - yarn

script:
  - npm run test
  - npm run build-lib

deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  tag: next
  on:
    branch: master
